# Generated by Django 4.2.11 on 2024-03-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='desc',
            field=models.TextField(blank=True, default='This is the description of a person, you can change if you want', null=True),
        ),
    ]
